Django_Simple/project2/books/urls.py
from django.urls import path
from . import views


app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('book/all/', views.book_list, name='book-list'),
    path('book/<int:pk>/', views.book_detail, name='book-detail'),
    path('author/all/', views.author_list, name='author-list'),
    path('author/<slug:slug>/', views.author_detail, name='author-detail'),
    path('comment/<int:pk>/', views.add_comment, name='add-comment'),
    path('genre/all/', views.genre_list, name='genre-list'),
    path('api/book/all', views.BookListApiView.as_view(), name='api-book-list'),
    path('api/author/all', views.AuthorListApiView.as_view(), name='api-author-list'),
]

# api for author_list

Django_Simple/project2/project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

Django_Simple/project2/books/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=32)
    # books

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    first = models.CharField(max_length=32)
    last = models.CharField(max_length=32)
    portrait = models.URLField(blank=True, null=True)
    info = models.TextField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    # books

    def __str__(self):
        return f'{self.first} {self.last}'

    # def get_genres(self):
    #     genres = []
    #     for book in self.books.all():
    #         for genre in book.genres.all():
    #             genres.append(genre)
    #     return set(genres)
    def get_genres(self):
        return Genre.objects.filter(books__author=self).distinct()

    class Meta:
        ordering = ['last', 'first']

    def get_absolute_url(self):
        return reverse(
            'books:author-detail',
            kwargs= {
                'slug': self.slug
            }
        )


class Book(models.Model):
    title = models.CharField(max_length=256)
    summary = models.TextField(blank=True, null=True)
    cover = models.URLField(blank=True, null=True)
    author = models.ForeignKey(Author, related_name='books', on_delete=models.SET_NULL, blank=True, null=True)
    genres = models.ManyToManyField(Genre, related_name='books', blank=True)
    # comments

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'books:book-detail',
            kwargs={
                'pk': self.id
            }
        )


class Comment(models.Model):
    username = models.CharField(max_length=64)
    text = models.CharField(max_length=256)
    published = models.DateTimeField(default=now)
    book = models.ForeignKey(Book, related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-published']

Django_Simple/project2/books/forms.py
from django.forms import ModelForm
from .models import *


class CommentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = ['username', 'text']

Django_Simple/project2/books/views.py
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import render
from rest_framework import generics

from .models import *
from .forms import *
from .serializers import *


# Create your views here.
def index(request):
    return render(
        request,
        template_name='books/index.html',
        context={
            'book_count': Book.objects.count(),
            'author_count': Author.objects.count(),
            'genre_count': Genre.objects.count(),

        }
    )


def book_list(request):
    object_list = Book.objects.select_related('author').annotate(num_comments=Count("comments")).order_by('title')
    # print(object_list[0].__dict__)
    return render(
        request,
        template_name='books/book_list.html',
        context={
            'object_list': object_list,
        }
    )


def book_detail(request, pk):
    return render(
        request,
        template_name='books/book_detail.html',
        context={
            'object': Book.objects.get(id__exact=pk),
            'comment_form': CommentForm()
        }
    )


def author_list(request):
    return render(
        request,
        template_name='books/author_list.html',
        context={
            'object_list': Author.objects.all(),
        }
    )


def author_detail(request, slug):
    return render(
        request,
        template_name='books/author_detail.html',
        context={
            'object': Author.objects.get(slug__exact=slug),
            'comments': Comment.objects.filter(book__author__slug__exact=slug).select_related('book'),
        }
    )


# def add_comment(request, pk):
#     book = Book.objects.get(id__exact=pk)
#     print(request.POST)
#     Comment.objects.create(
#         username=request.POST['username'],
#         text=request.POST.get('text'),
#         book=book
#     )
#     return HttpResponseRedirect(book.get_absolute_url())

def add_comment(request, pk):
    book = Book.objects.get(id__exact=pk)
    # print(request.POST)
    form = CommentForm(request.POST)
    new_comment = form.save(commit=False)
    new_comment.book = book
    new_comment.save()
    # print(new_comment)
    return HttpResponseRedirect(book.get_absolute_url())


def genre_list(request):
    return render(
        request,
        template_name='books/genre_list.html',
        context={
            'object_list': Genre.objects.prefetch_related('books__author'),
        }
    )


class BookListApiView(generics.ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class AuthorListApiView(generics.ListAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

Django_Simple/project2/books/templates/books/api_vue_authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios@1.1.2/dist/axios.min.js"></script>
    <title>Authors API</title>
</head>
<body>
    <h2>Authors</h2>
    <div class="row" id="app">
        <div v-for="author in info" class="col-3 text-center">
            <img :src=author.portrait class="w-75 h-50 object-fit-cover rounded">
            <p class="fs-3">
                {{ author.first }} {{ author.last }}
            </p>
            <p v-for="book in author.books">
                {{ book.title }}
            </p>
        </div>
    </div>
    <script>
        new Vue({
            el: '#app',
            data() {
                return {
                    info: null
                };
            },
            mounted() {
                axios
                    .get('http://127.0.0.1:8000/api/author/all')
                    .then(response => (this.info = response.data));
            }
        });
    </script>
</body>
</html>

Django_Simple/project2/books/templates/books/author_detail.html
{% extends 'books/base.html' %}


{% block title %}
    {{ object }}
{% endblock %}

{% block header %}
    <h1 class="text-primary text-center">
        {{ object }}
    </h1>
{% endblock %}

{% block content %}
    <div class="row mt-3">
        <div class="col-3">
            <img src="{{ object.portrait }}" class="w-75 my-3 rounded">
            <div>
                {% for genre in object.get_genres %}
                    <a href="#" class="m-2">
                        {{ genre }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-5 mt-3 border rounded" style="font-size: 120%; text-align: justify;">
            <div class="my-3">
                {{ object.info }}
            </div>
            <div>
                {% for book in object.books.all %}
                    <div class="row my-2">
                        <div class="col-2">
                            <img src="{{ book.cover }}" class="w-100">
                        </div>
                        <div class="col-5">
                            <a href="{{ book.get_absolute_url }}">
                                {{ book.title }}
                            </a>
                        </div>
                        
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-4">
            {% if comments %}
                <p class="fs-3"> 
                    Comments:
                </p>
                {% for comment in comments %}
                    <p>
                        {{ comment.username }} about <a href="{{ comment.book.get_absolute_url }}">{{ comment.book.title }}</a>: {{ comment }}
                        <span class="fst-italic text-secondary"> 
                            {{ comment.published }}
                        </span>
                    </p>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

Django_Simple/project2/books/templates/books/author_list.html
{% extends 'books/base.html' %}


{% block title %}
    All authors
{% endblock %}

{% block header %}
    <h1 class="text-primary text-center">
        All authors
    </h1>
{% endblock %}

{% block content %}
    <div class="row mt-3">
        {% for author in object_list %}
            <div class="col-3 text-center">
                <img src="{{ author.portrait }}" class="w-75 h-75 my-2 object-fit-cover rounded"><br>
                <a href="{{ author.get_absolute_url }}" class="fs-2">
                    {{ author }}
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Django_Simple/project2/books/templates/books/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" 
        crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'books/img/logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body class="bg-light">
    <div class="container">
        <div class="row my-1">
            <div class="col-1">
                <a href="{% url 'books:index' %}">
                    <img src="{% static 'books/img/logo.png' %}" class="w-75">
                </a>
            </div>
            <div class="col-10">
                {% block header %}
                {% endblock %}
            </div>
        </div>
        {% block content %}
        {% endblock %}
        {% include 'books/footer.html' %}
    </div>
</body>
</html>

Django_Simple/project2/books/templates/books/book_detail.html
{% extends 'books/base.html' %}


{% block title %}
    {{ object }}
{% endblock %}

{% block header %}
    <h1 class="text-primary text-center">
        {{ object }}
    </h1>
{% endblock %}

{% block content %}
    <div class="row mt-3">
        <div class="col-4">
            <a href="{{ object.author.get_absolute_url }}" class="fs-3">
                {{ object.author }}
            </a><br>
            <img src="{{ object.cover }}" class="w-75 my-3 rounded">
            <div>
                {% for genre in object.genres.all %}
                    <a href="#" class="m-2">
                        {{ genre }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-4 mt-5 border rounded" style="font-size: 120%; text-align: justify;">
            {{ object.summary }}
        </div>
        <div class="col-4">
            {% if object.comments.exists %}
                <p class="text-center fs-3 mt-5"> 
                    Comments:
                </p>
                {% for comment in object.comments.all %}
                    <p>
                        {{ comment.username }} : {{ comment }}
                        <span class="fst-italic text-secondary"> 
                            {{ comment.published }}
                        </span>
                    </p>
                {% endfor %}
            {% else %}
                <p class="text-center fs-3 mt-5"> 
                    There is no comments yet
                </p>
            {% endif %}
            <div class="my-3">
                <form method="post" action="{% url 'books:add-comment' pk=object.id %}">
                    {% csrf_token %}
                    {{ comment_form }}
                    <input type="submit" value="Add comment">
                </form>
            </div>
        </div>
        
    </div>
{% endblock %}

Django_Simple/project2/books/templates/books/book_list.html
{% extends 'books/base.html' %}


{% block title %}
    All books
{% endblock %}

{% block header %}
    <h1 class="text-primary text-center">
        All books
    </h1>
{% endblock %}

{% block content %}
    <div class="row mt-3">
        {% for book in object_list %}
            <div class="col-3 text-center">
                <a href="{{ book.author.get_absolute_url }}" class="fs-4">
                   {{ book.author }}
                </a><br>
                <img src="{{ book.cover }}" class="h-50 my-2 object-fit-fill rounded"><br>
                <a href="{{ book.get_absolute_url }}" class="fs-2">
                    {{ book.title }}
                </a>
                {% if book.num_comments > 0 %}
                    <p>
                        comments: {{ book.num_comments }}
                    </p>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

Django_Simple/project2/books/templates/books/footer.html
<div class="row justify-content-center mt-5">
    <div class="col-4">
        <p class="text-center">
            <i class="fa-regular fa-copyright"></i>
            All rights are reserved
        </p>
    </div>
</div>

<!-- template for books - view function and show all books-->

Django_Simple/project2/books/templates/books/genre_list.html
{% extends 'books/base.html' %}


{% block title %}
    All genres
{% endblock %}

{% block header %}
    <a name="top"></a>
    <h1 class="text-primary text-center">
        All genres
    </h1>
{% endblock %}

{% block content %}
    <div class="my-2">
        {% for genre in object_list %}
            <a href="#genre-{{ genre.id }}" class="mx-2">
                {{ genre.name }}
            </a>
        {% endfor %}    
    </div>
    {% for genre in object_list %}
        <a name="genre-{{ genre.id }}"></a>
        <h2 class="text-secondary mt-3">
            {{ genre }}
        </h2>
        <a href="#top" class="fs-3"><i class="fa-solid fa-circle-up"></i></a>
        <div class="row mt-3">
            {% for book in genre.books.all %}
                <div class="col-3 text-center">
                    <a href="{{ book.author.get_absolute_url }}" class="fs-4">
                       {{ book.author }}
                    </a><br>
                    <img src="{{ book.cover }}" class="w-75 h-50 my-2 object-fit-cover rounded"><br>
                    <a href="{{ book.get_absolute_url }}" class="fs-2">
                        {{ book.title }}
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

Django_Simple/project2/books/templates/books/index.html
{% extends 'books/base.html' %}


{% block title %}
    Artem's library
{% endblock %}

{% block header %}
    <h1 class="text-primary text-center">
        Artem's library
    </h1>
{% endblock %}

{% block content %}
    <div class="my-5" style="height: 100px;"></div>
    <div class="row justify-content-between mt-5">
        <div class="col-2 text-center border rounded py-5 bg-white">
            <i class="fa-solid fa-book-open" style="font-size: 400%;"></i><br>
            <a href="{% url 'books:book-list' %}" class="fs-1">Books({{ book_count }})</a>
        </div>
        <div class="col-2 text-center border rounded py-5 bg-white">
            <i class="fa-solid fa-user" style="font-size: 400%;"></i><br>
            <a href="{% url 'books:author-list' %}" class="fs-1">Authors({{ author_count }})</a>
        </div>
        <div class="col-2 text-center border rounded py-5 bg-white">
            <i class="fa-solid fa-masks-theater" style="font-size: 400%;"></i><br>
            <a href="{% url 'books:genre-list' %}" class="fs-1">Genres({{ genre_count }})</a>
        </div>
    </div>
{% endblock %}