Django_Simple/project1/polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('question/detail/<int:pk>/', views.question_detail, name='question-detail'),
    path('question/vote/<int:pk>/', views.question_vote, name='question-vote'),
    path('question/results/<int:pk>/', views.question_results, name='question-results'),
    path('question/add-answer/<int:pk>/', views.add_question_answer, name='add-question-answer'),
    path('question/new-answer/<int:pk>/', views.new_answer, name='new-answer'),
]

Django_Simple/project1/project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls.py')),

]

Django_Simple/project1/polls/models.py
from django.db import models
import datetime


# Create your models here.
class Question(models.Model):
    text = models.CharField(max_length=256)
    views = models.IntegerField(default=0)
    created = models.DateTimeField(default=datetime.datetime.now)
    # answers - field

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.CharField(max_length=256)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)  # SET_NULL

    def __str__(self):
        return self.text

Django_Simple/project1/polls/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Count, Sum
from . import models


# Create your views here.
def index(request):
    context = {
        'latest_question_list': models.Question.objects.order_by('-created')[:5],
        'most_viewed_question_list': models.Question.objects.order_by('-views')[:5],
        'most_answered_question_list': models.Question.objects.annotate(number_of_answers=Count('answers'))
                                       .order_by('-number_of_answers')[:5],
        'most_voted_question_list': models.Question.objects.annotate(sum_of_votes=Sum('answers__votes'))
                                       .order_by('-sum_of_votes')[:5],
    }
    return render(
        request,
        template_name='polls/index.html',
        context=context
    )


def question_detail(request, pk):
    question = models.Question.objects.get(id__exact=pk)
    question.views += 1
    question.save()
    context = {
        'object': question,
    }
    return render(
        request,
        template_name='polls/question_detail.html',
        context=context
    )


def question_vote(request, pk):
    if request.method == 'POST':
        answer_id = request.POST.get('answer-id')
        print(answer_id)
        if answer_id:
            answer = models.Answer.objects.get(id__exact=answer_id)
            print(answer)
            answer.votes += 1
            answer.save()
            return HttpResponseRedirect(
                reverse('polls:question-results', args=[pk])
            )
        else:
            context = {
                'object': models.Question.objects.get(id__exact=pk),
                'message': 'You must select one answer!'
            }
            return render(
                request,
                template_name='polls/question_detail.html',
                context=context
            )


def question_results(request, pk):
    question = models.Question.objects.get(id__exact=pk)
    context = {
        'object': question,
    }
    return render(
        request,
        template_name='polls/question_results.html',
        context=context
    )


def add_question_answer(request, pk):
    # INSERT
    # INTO
    # polls_answer(text, votes, question_id)
    # VALUES("Some text", 0, 1)
    if request.method == 'POST':
        question = models.Question.objects.get(id__exact=pk)
        new_answer_text = request.POST.get('new-answer')
        if new_answer_text:
            # 1
            # new_answer = models.Answer.objects.create(text=new_answer_text, question=question)
            # 2
            new_answer = models.Answer(text=new_answer_text, question=question)
            new_answer.save()
        return HttpResponseRedirect(
            reverse('polls:question-results', kwargs={
                'pk': pk
            })
        )


def new_answer(request, pk):
    question = models.Question.objects.get(id__exact=pk)
    context = {
        'object': question
    }
    return render(
        request,
        template_name='polls/add_questions_answer.html',
        context=context
    )

Django_Simple/project1/polls/templates/polls/add_questions_answer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object }} : results</title>
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'polls/img/raise-hand.png' %}" type="image/x-icon">
</head>
<body>
    <a href="{% url 'polls:index' %}">
        <img src="{% static 'polls/img/raise-hand.png' %}" width="70">
    </a>
    <div class="container">
        <h3>{{ object }} : Add an answer</h3>
        <form action="{% url 'polls:add-question-answer' pk=object.id %}" method="post">
            {% csrf_token %}
            <p>
                <input type="text" name="new-answer" placeholder="Input an answer" >
            </p>
            {% if message %}
                <p class="warning">
                    {{ message }}
                </p>
            {% endif %}
            <p>
                <input type="submit" value="Add answer">
            </p>
        </form>
<!-- add new answer form (input text) -->
    </div>
</body>
</html>

Django_Simple/project1/polls/templates/polls/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'polls/img/raise-hand.png' %}" type="image/x-icon">
</head>
<body>
    <a href="{% url 'polls:index' %}">
        <img src="{% static 'polls/img/raise-hand.png' %}" width="70">
    </a>
    <div class="container">
        <div class="block">
            <h3>Latest questions</h3>
            {% for q in latest_question_list %}
                <a href="{% url 'polls:question-detail' pk=q.id %}">
                    <p>
                        {{ q }}
                    </p>
                </a>
                <span>
                    {{ q.created }}
                </span>
            {% endfor %}
        </div>
        <div class="block">
            <h3>Most viewed questions</h3>
            {% for q in most_viewed_question_list %}
                <a href="{% url 'polls:question-detail' pk=q.id %}">
                    <p>
                        {{ q }}
                    </p>
                </a>
                <span>
                    Views: {{ q.views }}
                </span>
            {% endfor %}
        </div>
        <div class="block">
            <h3>Most answered questions</h3>
            {% for q in most_answered_question_list %}
                <a href="{% url 'polls:question-detail' pk=q.id %}">
                    <p>
                        {{ q }}
                    </p>
                </a>
                <span>
                    Answers: {{ q.number_of_answers }}
                </span>
            {% endfor %}
        </div>
        <div class="block">
            <h3>Most voted questions</h3>
            {% for q in most_voted_question_list %}
                <a href="{% url 'polls:question-detail' pk=q.id %}">
                    <p>
                        {{ q }}
                    </p>
                </a>
                <span>
                    Votes: {{ q.sum_of_votes }}
                </span>
            {% endfor %}
        </div>
    </div>
</body>
</html>

Django_Simple/project1/polls/templates/polls/question_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object }}</title>
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'polls/img/raise-hand.png' %}" type="image/x-icon">
</head>
<body>
    <a href="{% url 'polls:index' %}">
        <img src="{% static 'polls/img/raise-hand.png' %}" width="70">
    </a>
    <div class="container">
        <h3>{{ object }} : Vote Form</h3>
        <p>
            Created at: {{ object.created }} <br>
            Views: {{ object.views }}
        </p>
        <form action="{% url 'polls:question-vote' pk=object.id %}" method="post">
            {% csrf_token %}
            {% for a in object.answers.all %}
                <p>
                    <input type="radio" name="answer-id" value="{{ a.id }}" id="answer-{{ a.id }}">
                    <label for="answer-{{ a.id }}">
                        {{ a.text }}
                    </label> 
                </p>
            {% endfor %}
            {% if message %}
                <p class="warning">
                    {{ message }}
                </p>
            {% endif %}
            <p>
                <input type="submit" value="Vote">
            </p>
        </form>
        <a href="{% url 'polls:new-answer' pk=object.id %}">
            Add answer for current question
        </a>
    </div>
</body>
</html>

Django_Simple/project1/polls/templates/polls/question_results.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object }} : results</title>
    <link rel="stylesheet" href="{% static 'polls/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'polls/img/raise-hand.png' %}" type="image/x-icon">
</head>
<body>
    <a href="{% url 'polls:index' %}">
        <img src="{% static 'polls/img/raise-hand.png' %}" width="70">
    </a>
    <div class="container">
        <h3>{{ object }} : Vote Results</h3>
        <p>
            Created at: {{ object.created }} <br>
            Views: {{ object.views }}
        </p>
        <table class="table-results">
            <tr>
                <td>
                    Answer
                </td>
                <td>
                    Votes
                </td>
            </tr>
            {% for a in object.answers.all|dictsortreversed:'votes' %}
                <tr>
                    <td>
                        {{ a.text }}
                    </td>
                    <td>
                        {{ a.votes }}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href="{% url 'polls:question-detail' pk=object.id %}">
            Vote again
        </a>
    </div>
</body>
</html>